BlogBundle\Entity\Tag:
    properties:
        name:
            - NotBlank: {message: "El nombre no puede estar vacío"}
            - Length:
                min: 4
                minMessage: "El nombre tiene que tener más de 2 caracteres"
                
BlogBundle\Entity\Category:
    properties:
        name:
            - NotBlank: {message: "El nombre no puede estar vacío"}
            - Length:
                min: 4
                minMessage: "El nombre tiene que tener más de 2 caracteres"
